"""Scaffolding files for the emitted suite: package.json, playwright.config.ts, README.md."""

from __future__ import annotations

PACKAGE_JSON = """{{
  "name": "Anjalikastra-suite",
  "version": "1.0.0",
  "private": true,
  "description": "Generated end-to-end/functional test suite for {base_url} — produced by Anjalikastra.",
  "scripts": {{
    "test": "playwright test",
    "test:headed": "playwright test --headed",
    "report": "playwright show-report"
  }},
  "devDependencies": {{
    "@playwright/test": "^1.44.0"
  }}
}}
"""

PLAYWRIGHT_CONFIG = """import {{ defineConfig, devices }} from '@playwright/test';

export default defineConfig({{
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: [['html', {{ open: 'never' }}], ['list']],
  use: {{
    baseURL: process.env.BASE_URL || '{base_url}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  }},
  projects: [
    {{ name: 'chromium', use: {{ ...devices['Desktop Chrome'] }} }},
  ],
}});
"""

README = """# {base_url} — generated E2E/functional test suite

This suite was generated by [Anjalikastra](https://github.com/) against the live
site `{base_url}` on {generated_at}. It exercises the pages and API endpoints that
were reachable **without authentication** at generation time — see the coverage
section of `report.md` in the run output for what was (and wasn't) reached.

These are end-to-end / functional / smoke tests driven against the live site, not
unit tests — there is no source-code access involved in producing them.

## Running the suite

```bash
npm install
npx playwright install --with-deps chromium
npm test
```

Override the target with `BASE_URL`:

```bash
BASE_URL=https://staging.example.com npm test
```

## Structure

- `tests/pages/*.spec.ts` — one file per page or closely related group of pages.
- `tests/api/*.spec.ts` — one file per API endpoint or resource.
- `playwright.config.ts` — base URL, retries, reporters.

## Interpreting results

- `npm test` runs headless; `npm run test:headed` watches it run.
- `npm run report` opens the last HTML report (screenshots + traces on failure).
- A failing test here may mean the site changed since generation, not necessarily
  a bug — re-run Anjalikastra to regenerate against the current site if the suite
  drifts out of date.

## Maintaining these tests

This suite is meant to be kept, not thrown away. Edit it like hand-written tests —
add assertions as you learn more about the app, delete tests for pages that go away.
"""


def render_package_json(base_url: str) -> str:
    return PACKAGE_JSON.format(base_url=base_url)


def render_playwright_config(base_url: str) -> str:
    return PLAYWRIGHT_CONFIG.format(base_url=base_url)


def render_readme(base_url: str, generated_at: str) -> str:
    return README.format(base_url=base_url, generated_at=generated_at)
