# Navigation Links
main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: GitHub ↗
    url: https://github.com/khushaljethava/Anjalikastra
    weight: 30
