title: Anjalikastra
email: khushaljethava@gmail.com
description: >-
  Anjalikastra documentation landing page for GitHub Pages.
baseurl: ""
url: "https://khushaljethava.work/Anjalikastra"

markdown: kramdown
permalink: pretty

plugins: []
